### ISSUE TITLE
New check: Warn if a font is likely to preview as "Σ√≠" rather than "Abg" in Windows Font Settings

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fontspector#169]
## What needs to be checked?

The Windows Font Settings panel displays fonts with icons to preview their general look. Unfortunately, many fonts preview as "Σ√≠" rather than "Abg," which isn’t very helpful. 

![](https://typo.social/system/media_attachments/files/112/272/921/318/512/506/original/1e4e09ad05937cf9.png)

This seems like a Windows bug, as it occurs even when fonts are straightforwardly meant for Latin text, and just happen to include OS/2 information that they include glyphs in the [Mathematical Operators Unicode Block](https://en.wikipedia.org/wiki/Mathematical_Operators_(Unicode_block)). This bit seems to be checked by FontMake builds for almost all fonts, if they contain glyphs in this block, such as the `/` (the basic forward slash).

FontMake seems to be working properly by doing this, but it seems to be fairly common practice for foundries to uncheck the Mathematical Operators bit of the Unicode Page Ranges, to workaround this Windows bug.

## Detailed description of the problem 

This seems to be a long-running issue. I’m seeing it on Windows 11, 22H2. However, the bug (and the workaround) is documented at least as early as 2015 [on TypeDrawers](https://typedrawers.com/discussion/1174/font-preview-icons-in-windows). Recent discussion at https://typo.social/@arrowtype/112272933176102051 shows that it is a fairly common problem, and that a common workaround is to removed the math operators bit.

It is possible there are more in-depth factors at play, as the bug doesn’t occur on every font that includes the math operators bit. For example, when fonts do have the "math operators" bit set but don’t include specific PANOSE information, this usually doesn’t seem to occur (e.g. in Shantell Sans). You’d think this might be due to the presence of a meta table, but that doesn’t always seem to be the case (again, in Shantell Sans).

However, it does seem like removing that bit is a reliable way to avoid the bug, so unless there is a better way, or unless/until we can somehow convince MS to fix the bug, it seems like something worth making a FontBakery check to flag.

## Resources and steps needed to reproduce the problem

A frustrating part of this problem is that it seems easy enough to avoid by removing the math operators bit, but there are also examples of fonts that do include this, and don’t exhibit the problem. For example, Shantell Sans, Recursive, and Ubuntu all preview as "Abg," despite having this bit set. But, clearly this is a well-known, long running problem, so it would be good to alert font makers if there is known workaround. I’ve had it happen to multiple recent fonts created with FontMake and GF Builder workflows.

## Suggested profile

Suggest which profile the check should be added to. The most common are:

Universal (Probably?)

## Suggested result

Which log result level should the check have:

⚠️ **WARN** (A potential issues that may need to be addressed)

## Severity assessment

2 or 3. It makes the font appear somewhat broken or janky on Windows, but it doesn’t seem to have any further impact.

**Comment by mgbella** [comment]
@arrowtype Thanks for creating this; I've meant to do it for a long time. It's just been part of my own workflow to do an install test and manually check it. Until it's fixed by MS or until someone can pinpoint the exact culprit, the WARN is exactly what I would hope for as well—at least to flag it so it could be checked manually. AFAIK, the `Σ√≠ `bug is purely cosmetic. 

Cheers.

**Comment by Hoolean** [comment]
@arrowtype Hi Stephen! I have a Q on this if you wouldn't mind: in your findings did the languages in [the `meta` table](https://learn.microsoft.com/en-us/typography/opentype/spec/meta) ever have an influence on this, or were they only useful for unrelated OS functionality?

**Comment by arrowtype** [comment]
@Hoolean interesting question! I don’t believe I tested that aspect, but I would welcome additional information or testing, if you’ve looked into it.

Based on [this issue](https://github.com/fonttools/fontbakery/issues/4408), it sounds like Windows is only using this table relatively recently. I would guess that, if it does have any effect, it would be limited to the newer settings overview of Windows 11. However, this "Σ√≠" issue is more specific to the classic control panel fonts view. 

Additionally, just based on my screenshot in the initial comment, you can see that Name Mono is affected by this issue, while Name Sans is not. Neither family has that table in any of their fonts, as of now. So, I think that suggests that this is not caused by the meta table. I doubt it would be solved by the meta table, but again, I would welcome any information if you have more!

**Comment by Hoolean** [comment]
Awesome, thanks for the speedy confirmation : )

> [...] I would welcome additional information or testing, if you’ve looked into it.

We originally heard through the grapevine that `meta` might fix the thumbnail, but we've not been able to trace it back to a particular working example, nor replicate through practical testing, and so I think it's safe for us to conclude that it doesn't fix it. We also share the conclusion that Unicode bit hacking is likely the only way to go here.
 
(We suspect this arose through `meta`'s mention in adjacent discussions, with regards to its more typical and very useful applications in Windows/macOS font viewers, fallbacks and preferences)
